name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
    - name: Report Arm GCC Version
      run: arm-none-eabi-gcc --version
    - name: Run a full build
      run: make all
    - name: Upload built file
      uses: actions/upload-artifact@v3
      with:
        name: T-962-controller.hex
        path: ./build/T-962-controller.hex

